version = "1"

[phases.backend-setup]
# Setup backend dependencies
commands = [
    "pip install -r backend/requirements.txt"
]

[phases.frontend-setup]
# Setup frontend dependencies
commands = [
    "npm install --prefix frontend"
]

[phases.frontend-build]
# Build frontend assets if necessary
commands = [
    "npm run build --prefix frontend"
]

[phases.backend-start]
# Start the backend
commands = [
    "python backend/server.py"
]

[phases.frontend-start]
# Start the frontend
commands = [
    "npm start --prefix frontend"
]

# Specify environment variables
[env]
# Add any environment variables for the backend here
FLASK_ENV = "production"
PORT = "8000"

# Specify the backend language and version (Python)
[language.backend]
name = "python"
version = "3.10"

# Specify the frontend language and version (Node.js)
[language.frontend]
name = "node"
version = "16"

# Additional packages or system dependencies
[packages]
list = [
    "git",
    "curl"
]
