version = "1"

# Backend setup and dependencies installation
[phases.backend-setup]
commands = [
    "pip install -r backend/requirements.txt"
]

# Frontend setup and dependencies installation
[phases.frontend-setup]
commands = [
    "npm install --prefix frontend"
]

# Frontend build process
[phases.frontend-build]
commands = [
    "npm run build --prefix frontend"
]

# Combined start command for both backend and frontend
[phases.start]
commands = [
    "python backend/server.py & npm start --prefix frontend"
]

# Environment variables (optional)
[env]
FLASK_ENV = "production"
PORT = "8000"

# Specify the backend language (Python)
[language.backend]
name = "python"
version = "3.10"

# Specify the frontend language (Node.js)
[language.frontend]
name = "node"
version = "16"

# Additional packages (optional)
[packages]
list = [
    "git",
    "curl"
]
