# Define the phases of the build
[build]
# Setup both backend and frontend dependencies
setup = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

# Build frontend assets if necessary
build = [
    "cd frontend && npm run build",
    "cd backend && python server.py"
]

[start]
# Start both the backend and frontend
cmd = "cd backend && python server.py & cd frontend && npm start"

# Specify the backend environment variables
[env]
# Add any environment variables for the backend here
FLASK_ENV = "production"
PORT = "8000"

# Specify the language and version for the backend (Python)
[python]
version = "3.10"

# Additional packages or system dependencies
[packages]
list = [
    "git",
    "curl"
]
